### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Nchedubem**
please kindly review my work
@Promise-J
@ChidiPatrick
Group A

### CODE REVIEW

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work @Nchedubem. I suggest you make the nav links text fontsize to be reduced across tablets and mobile screens. That's my only change. I LOVE THIS 💯

**Comment by Nchedubem** [comment]
I have done it

**Review by promise-J — APPROVED** [review]
You have dwelt so long on this project.
I am not too pleased with this work and it seems you are not even seeing what I am seeing
Just to move on, please hide the nav links on mobile screen sized. 
You can now merge it. This is not of a great standard

**Review by promise-J — APPROVED** [review]
You have dwelt so long on this project.
I am not too pleased with this work and it seems you are not even seeing what I am seeing
Just to move on, please hide the nav links on mobile screen sized. 
You can now merge it. This is not of a great standard

**Comment by Nchedubem** [comment]
I have made the correct
Please Sir Kindly Review my work
Thanks & Regards

**Review by promise-J — APPROVED** [review]
You are cleared to merge

**Pull request merged**
